### ISSUE TITLE
Discussion of the content of the package

### ISSUE THREAD

**Issue by yhan178** [UBC-MDS/wordwright#2]

**Comment by yhan178** [comment]
Package name: text_processing_group4 etc.
Load_text
Clean/punctuation + common words: the’ ‘a’. ..etc. + visualization top 10 most frequent (word cloud).
Count keywords/keyword extraction, restore, restoration, restor*
Count number sentences, length of the text.
Language Detection (is English or not)

**Comment by jinyz8888** [comment]
Agree.
