### ISSUE TITLE
write a unit tests for language_detection()

### ISSUE THREAD

**Issue by yhan178** [UBC-MDS/wordwright#25]
- The unit tests should test at least 3 to 5 edge of the most important cases to ensure that the function returns what is expected to the user. 
- It should also test for expected errors. 
- When writing your tests, build them around your function specifications and requirements.
- Document your test functions

**Comment by jinyz8888** [comment]
Unit tests for it is done, see https://github.com/UBC-MDS/wordwright/commit/e2bdfa122687258449f77d54ac521d64cbc006ca
