### ISSUE TITLE
write a unit tests for frequent_words()

### ISSUE THREAD

**Issue by yhan178** [UBC-MDS/wordwright#28]
- The unit tests should test at least 3 to 5 edge of the most important cases to ensure that the function returns what is expected to the user. 
- It should also test for expected errors. 
- When writing your tests, build them around your function specifications and requirements.
- Document your test functions

**Comment by yhan178** [comment]
unit tests for `frequent_words()` done, see details here https://github.com/UBC-MDS/wordwright/commit/438be722fce4da75f9d7b1b8d71716d9404e4625

**Comment by carrieyanyi** [comment]
well done!
