### ISSUE TITLE
Write a unit tests for load_text() and clean_text()

### ISSUE THREAD

**Issue by yhan178** [UBC-MDS/wordwright#29]
- The unit tests should test at least 3 to 5 edge of the most important cases to ensure that the function returns what is expected to the user. 
- It should also test for expected errors. 
- When writing your tests, build them around your function specifications and requirements.
- Document your test functions

**Comment by yhan178** [comment]
Finish unit tests for load_text() and clean_text(), see https://github.com/UBC-MDS/wordwright/commit/ff50e149c55cb58518cbf2ce06e34baf1e3740f4 and https://github.com/UBC-MDS/wordwright/commit/435d61dfd62dd064d9ff53df8d3aa3ac76e6d352.

**Comment by carrieyanyi** [comment]
thank you!
