### ISSUE TITLE
write code for function count_sentences()

### ISSUE THREAD

**Issue by yhan178** [UBC-MDS/wordwright#30]
- Think critically about what function inputs you expect from the user and what your function is supposed to do (e.g., return). 
- The function should be written defensively. That is, **it should handle incorrect input and errors detected during execution via throwing exceptions with useful error messages**.
- After writing your unit tests, write the internal code for your functions. Write function code and tests in close temporal proximity with each other. The process of writing function code and test cases will be iterative;
- Make sure that the tests cover all code branches (e.g., if your function has an if statement, you should have tests where the if statement is true, and where the if statement is false.
- update your code documentation so that it makes sense with any of the changes you have made.

**Comment by carrieyanyi** [comment]
done https://github.com/UBC-MDS/wordwright/commit/950dc049b57cf78431dec1c30d81c18daffce4e1

**Comment by carrieyanyi** [comment]
finally updated
