### ISSUE TITLE
write a unit tests for count_sentences()

### ISSUE THREAD

**Issue by yhan178** [UBC-MDS/wordwright#31]
- The unit tests should test at least 3 to 5 edge of the most important cases to ensure that the function returns what is expected to the user. 
- It should also test for expected errors. 
- When writing your tests, build them around your function specifications and requirements.
- Document your test functions

**Comment by carrieyanyi** [comment]
done https://github.com/UBC-MDS/wordwright/commit/5cddc03bae50909941643e7e3a6b716c11ef0a45

**Comment by carrieyanyi** [comment]
more update on text file
