### ISSUE TITLE
Group meeting during DSCI 524 lab01 on Monday.

### ISSUE THREAD

**Issue by yhan178** [UBC-MDS/wordwright#32]
During the meeting, we have discussed:
1. Each team member's responsibility, finishing corresponding functions and unit tests.
2. Set up milestone/tasks/issues and assign tasks for each team member.
3. Next meeting on Friday 9 am in person.

**Comment by yhan178** [comment]
Meeting minutes:

**Comment by carrieyanyi** [comment]
well done!
