### ISSUE TITLE
write function specifications and documentation

### ISSUE THREAD

**Issue by yhan178** [UBC-MDS/wordwright#4]

**Comment by yhan178** [comment]
We break up our tasks into five functions. Each person will be responsible for one project
1. load_text & clean_text: Yi Han
3. count_keywords: Hongyang zhang
4. count_sentences_and_length: Yi Yan
5. language_detection: Yingzi Jin

**Comment by jinyz8888** [comment]
Completed documentation on the function language_detection

**Comment by carrieyanyi** [comment]
Completed documentation on the function count_sentense_length

**Comment by yhan178** [comment]
Complet documentation on the function load_text, clean_text, frequent_words
