### ISSUE TITLE
Monday lab1 meeting minutes

### ISSUE THREAD

**Issue by yhan178** [UBC-MDS/wordwright#49]
In Monday's meeting, we discuss the focus of this week's milestone focus and split up the tasks.

**_1. Environment and packages_**
- [x] set up environment and add necessary packages for publishing documentation. -- Yingzi

**_2. Vignettes_**
- [x]  strong overview and motivation for our package. -- Carrie

Write narrative demonstration of the package functions
- [x] `load_text()` & `clean_text()` -- Hayley
- [x] `word_frequency()` -- Hayley
- [x] `language_detection()` -- Yingzi
- [x] `count_keywords()` -- Hongyang
- [x] `count_sentence()` -- Carrie

**_3. Publishing the package-level documentation_**
- [x] Proofreading of documentation: readme, docstrings and vignettes. -- Everyone during Friday meeting
- [x] Publishing the package-level documentation. -- Everyone during Friday meeting

**Comment by carrieyanyi** [comment]
good job!
