### ISSUE TITLE
Read me update

### ISSUE THREAD

**Issue by yhan178** [UBC-MDS/wordwright#69]
From reviewer  1
- I know the link to your documentation is included in the docs badge, but it would be worth also including it in the 'about' section on the homepage of your repo just to make it extra easy to find.
- Add a 'statement of need' section in the README file to give a description of the problems the package is designed to solve and to elaborate on what separates wordwright from similar packages that already exist (if there are any).
- Add a citation section to acknowledge any functions that your package is dependent on or any other information cited or used in the development of the package.

From reviewer 2
- Metadata: It would be helpful to list the core contributors near the top of the README, and possibly include hyperlinks to their profiles (rather than @ their handle) as it is more user friendly.
- README installtion troubleshooting: The installation section was very friendly for users, but some sections were a little vague (e.g., under "Poetry installation issues", I wasn't sure what you meant by ensuring that pyproject.toml is "properly configured" - do you mean making sure that the format is up to date with the current standard? It might be helpful to provide a link to the documentation on pyproject.toml if that's what you were referring to.

From reviewer 3:
-

**Comment by carrieyanyi** [comment]
solve all corresonding issues
