### ISSUE TITLE
badge update

### ISSUE THREAD

**Issue by yhan178** [UBC-MDS/wordwright#73]
Reviewer 1:
- badge: A [repostatus.org](http://repostatus.org/) badge, Current package version (on PyPI / Conda

Reviewer 3:
- Badge for related information are missing that are required by the package guideline. Namely, the currently release version on PyPI./conda.
- Consider to add a link to the readthedocs site. Currently the only link to the site is the doc passing badge.

**Comment by carrieyanyi** [comment]
done
